# .github/workflows/ci.yml
name: 'Integracion Continua de Login' # <-- Este nombre ahora SI funcionará

on:
  push:
    branches: [ "main" ]  # <--- ¡CORREGIDO! Ahora dispara en 'main'
  pull_request:
    branches: [ "main" ] 

jobs:
  test_login:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Obtener el codigo (Checkout)
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 3. Instalar Dependencias (npm install)
        run: npm install

      - name: 4. Ejecutar las Pruebas Unitarias (Jest)
        run: npm test